default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dns-api-coding-challenge_development

test:
  <<: *default
  database: dns-api-coding-challenge_test

production:
  <<: *default
  database: dns-api-coding-challenge_production
  username: dns-api-coding-challenge
  password: <%= ENV['DNS-API-CODING-CHALLENGE_DATABASE_PASSWORD'] %>
